[project]
name = "pop-goes-the-corn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "channels[daphne]>=4.2.0",
    "django>=5.1.6",
]

[dependency-groups]
dev = [
    "ruff>=0.9.9",
]
