# Generated by Django 5.1.6 on 2025-03-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_usergame_is_active_usergame_next_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='next_player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prev_player', to='game.usergame'),
        ),
    ]
