# Generated by Django 5.1.6 on 2025-03-01 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chance_to_draw',
            field=models.SmallIntegerField(default=75, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
